# Elements Page Properties

#### Buttons Content
textDClick = You have done a double click
textRClick = You have done a right click
textSClick = You have done a dynamic click
textDisabled = Disabled button

### CheckBox Content
textNinjaCh = Ninja is Disabled and Checked.
textAutoCh = Automation is Enabled and Checked.
textPerfCh = Performance is Enabled and Checked.
textAutoUn = Automation is Enabled and Unchecked.
textPerfUn = Performance is Enabled and Unchecked.
textFuncUn = Functional is Disabled and Unchecked.

### RadioButton Content
textDescription = Select your range of experience on QA Software
textInpName = Insert your Name
textOutMessage = Please enter your name.,Please select a range of time from QA Software Experience,you have selected that you have

### TextBox Content
textNameError = Name is required.
textEmailError =Email is required.
textDescriptionError = Description is required.
textOutView = Please correct the errors in the form.,Name:
textNamePlaceholder = e.g. Cesar Solorio
textEmailPlaceholder = e.g. cesar.solorio@mail.com
textDescriptionPlaceholder = e.g. This project is just for testing
