# Main Page Properties

#### Content
textFooter = Website designed & developed by Cesar A. Solorio
textMainContent = This project outlines the development of a dedicated website designed exclusively for testing purposes. This platform will house a diverse array of elements and navigation options, meticulously crafted to facilitate the development and refinement of automation frameworks for Software Development Engineers in Test (SDETs).

#### Menu
textMenu = Principal, Elements, Interactions, Widgets, Windows
textElemMenu = Buttons, CheckBox, RadioButton, Sliders, TextBox
textIntMenu = API
textWidMenu = Accordion, DatePicker, DropDown, Menu, Tabs
textWinMenu = Alerts, Frames, Windows

