# Widgets Page Properties

#### Accordion Content
textTabAccordion = Purposes of Software QA and Testing,Functional Testing,Non-Functional Testing
textContentAccordion = Quality Assurance (QA) in software testing is a systematic process to ensure that software products and services meet specified requirements and quality standards,Functional testing is a type of software testing that verifies each function of the software application operates in conformance with the requirement specifications,Non-functional testing is a type of software testing that evaluates the 'how' aspects of a system's operation

#### DatePicker Content
textNoContent = Please select a date first.
textContent = You have selected the date:
